FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /app

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .

RUN alembic upgrade head

EXPOSE 8000

CMD gunicorn 'main:create_app()' --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
